export const SCENES = {
    CONTROLS: "CONTROLS",
    HELP: "HELP",
    LEVEL_SELECT: "LEVEL_SELECT",
    MAIN_MENU: "MAIN_MENU",
    PRELOAD: "PRELOAD",
    SPLASH: "SPLASH",
    DAY: "DAY",
    NIGHT: "NIGHT"
}
