export const SCENES = {
    CONTROLS: "CONTROLS",
    HELP: "HELP",
    LEVEL_SELECT: "LEVEL_SELECT",
    MAIN_MENU: "MAIN_MENU",
    PAUSE: "PAUSE",
    PRELOAD: "PRELOAD",
    SPLASH: "SPLASH",
    DAY: "DAY",
    NIGHT: "NIGHT",
    DAY_OVERLAY:"DAY_OVERLAY"
}
