export const SCENES = {
    CONTROLS: "CONTROLS",
    HELP: "HELP",
    LEVEL_SELECT: "LEVEL_SELECT",
    MAIN_MENU: "MAIN_MENU",
    PAUSE: "PAUSE",
    PRELOAD: "PRELOAD",
    SPLASH: "SPLASH",
    DAY: "DAY",
    NIGHT: "NIGHT",
    DAY_OVERLAY:"DAY_OVERLAY",
    BEGINNING:"BEGINNING",
    DUNGEON3:"DUNGEON3",
    TUTORIAL:"TUTORIAL",
    MINI_DUNGEON:"MINI_DUNGEON",
    DUNGEON1:"DUNGEON1",
    DUNGEON2:"DUNGEON2",
    DUNGEON3:"DUNGEON3",
    DUNGEON4:"DUNGEON4",
    DUNGEON5:"DUNGEON5",
    NIGHT1: "NIGHT1",
    NIGHT2: "NIGHT2",
    NIGHT3: "NIGHT3",
    DAY_NIGHT_TRANSITION:"DAY_NIGHT_TRANSITION"


}
