export const SCENES = {
    CONTROLS: "CONTROLS",
    HELP: "HELP",
    LEVEL_SELECT: "LEVEL_SELECT",
    MAIN_MENU: "MAIN_MENU",
    PAUSE: "PAUSE",
    PRELOAD: "PRELOAD",
    SPLASH: "SPLASH",
    DAY: "DAY",
    NIGHT: "NIGHT",
    DAY_OVERLAY:"DAY_OVERLAY",
    DUNGEON2:"DUNGEON2",
    BEGINNING:"BEGINNING",
    DUNGEON3:"DUNGEON3",
    TUTORIAL:"TUTORIAL",
    DUNGEON1:"DUNGEON1",
    DAY_NIGHT_TRANSITION:"DAY_NIGHT_TRANSITION"


}
